services:
  - type: web
    name: distrito-burger-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TZ
        value: America/Bogota
