-- ==============================================================================
-- FASE 11: VERIFICACIÓN Y CREACIÓN DE TABLAS DE INVENTARIO Y RECETAS
-- ==============================================================================

-- 1. Insumos (Inventory Items)
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    unit_measure TEXT NOT NULL, -- ej: und, gr, ml
    current_stock NUMERIC DEFAULT 0,
    minimum_stock NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Recetas (Qué gasta cada combo/producto)
CREATE TABLE IF NOT EXISTS public.recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL, -- Hace referencia al ID del combo/producto
    inventory_item_id BIGINT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    quantity_required NUMERIC NOT NULL, -- Cantidad de insumo por cada unidad de producto vendido
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Bitácora de Compras (Purchases)
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    quantity NUMERIC NOT NULL,
    unit_price NUMERIC NOT NULL,
    total_price NUMERIC NOT NULL,
    purchase_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Transacciones Históricas (Entradas y Salidas generales)
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    quantity_change NUMERIC NOT NULL, -- Positivo = Entrada, Negativo = Salida
    reason TEXT, -- Ej: 'venta', 'compra', 'merma', 'ajuste'
    reference_id TEXT, -- Teléfono del cliente si es venta, o ID de compra
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Política de RLS (Para permitir lectura/escritura pública temporalmente)
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "inventory_items_policy" ON public.inventory_items FOR ALL USING (true);

ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "recipe_ingredients_policy" ON public.recipe_ingredients FOR ALL USING (true);

ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "purchases_policy" ON public.purchases FOR ALL USING (true);

ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "inventory_transactions_policy" ON public.inventory_transactions FOR ALL USING (true);
